# Generated by Django 2.1.5 on 2019-02-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0004_auto_20190219_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
