# Generated by Django 2.1.5 on 2019-02-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0005_auto_20190220_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('object_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('availability', models.CharField(choices=[('Y', 'Available'), ('N', 'Unavilable')], default='Y', max_length=1)),
                ('max_time', models.IntegerField()),
                ('location', models.CharField(choices=[('T', 'Turing'), ('H', 'Hopper')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
