# Generated by Django 2.1.5 on 2019-02-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0006_auto_20190225_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='location',
            field=models.CharField(choices=[('T', 'Turing'), ('H', 'Hopper')], default='H', max_length=1),
        ),
    ]
