# Generated by Django 2.1.5 on 2019-03-26 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0007_auto_20190226_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=1)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RFID.Object')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RFID.User')),
            ],
        ),
    ]
