# Generated by Django 2.1.5 on 2019-03-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0008_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='records',
            unique_together={('user_id', 'object_id', 'date')},
        ),
    ]
