# Generated by Django 2.1.5 on 2019-03-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0009_auto_20190327_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='active',
        ),
        migrations.AddField(
            model_name='records',
            name='type',
            field=models.CharField(choices=[('1', 'Check out'), ('0', 'Check in')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
