# Generated by Django 2.1.5 on 2019-04-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0010_auto_20190329_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RFID.Object'),
        ),
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Completed')], default='1'),
        ),
        migrations.AlterField(
            model_name='records',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RFID.User'),
        ),
    ]
