# Generated by Django 2.1.5 on 2019-04-07 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0011_auto_20190407_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RFID.Object'),
        ),
        migrations.AlterField(
            model_name='records',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RFID.User'),
        ),
    ]
