# Generated by Django 2.1.5 on 2019-04-08 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0012_auto_20190407_2305'),
    ]
    
