# Generated by Django 2.1.5 on 2019-04-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0013_auto_20190408_0413'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='records',
            unique_together={('user_id', 'object_id', 'date')},
        ),
    ]
