# Generated by Django 2.1.5 on 2019-04-08 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0014_auto_20190408_0418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='records',
            unique_together={('user_id', 'object_id', 'date')},
        ),
    ]
