# Generated by Django 2.1.5 on 2019-04-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0015_auto_20190408_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
