# Generated by Django 2.1.5 on 2019-04-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0016_auto_20190408_0423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='records',
            unique_together={('user_id', 'object_id', 'date')},
        ),
    ]
