# Generated by Django 2.1.5 on 2019-04-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0017_auto_20190408_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
