# Generated by Django 2.1.5 on 2019-04-08 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0018_auto_20190408_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
