# Generated by Django 2.1.5 on 2019-04-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0019_records_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='time',
        ),
    ]
