# Generated by Django 2.1.5 on 2019-04-15 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0020_remove_records_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='records',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
